== PP-Module for WLAN Clients

[cols="1,1,1,1,1,1,1,1"]
|===
8+|wlanclient 
| https://github.com/commoncriteria/wlanclient/tree/master[master] 
a| https://commoncriteria.github.io/wlanclient/master/wlanclient-release.html[📄]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/master/transforms.svg[transforms,150]
a| 
https://commoncriteria.github.io/wlanclient/master/wlanclient-release-linkable.html[wlanclient-release-linkable.html] +
https://commoncriteria.github.io/wlanclient/master/wlanclient-release.html[wlanclient-release.html] +
https://commoncriteria.github.io/wlanclient/master/wlanclient-sd.html[wlanclient-sd.html] +
https://commoncriteria.github.io/wlanclient/master/wlanclient.html[wlanclient.html] +
| https://github.com/commoncriteria/wlanclient/tree/release-1.0[release-1.0] 
a| https://commoncriteria.github.io/wlanclient/release-1.0/wlanclient-release.html[📄]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/release-1.0/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/release-1.0/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/release-1.0/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/release-1.0/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/release-1.0/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/release-1.0/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/wlanclient/blob/gh-pages/release-1.0/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/release-1.0/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/wlanclient/gh-pages/release-1.0/transforms.svg[transforms,150]
a| 
https://commoncriteria.github.io/wlanclient/release-1.0/wlanclient-release-linkable.html[wlanclient-release-linkable.html] +
https://commoncriteria.github.io/wlanclient/release-1.0/wlanclient-release.html[wlanclient-release.html] +
https://commoncriteria.github.io/wlanclient/release-1.0/wlanclient-sd.html[wlanclient-sd.html] +
https://commoncriteria.github.io/wlanclient/release-1.0/wlanclient.html[wlanclient.html] +
|===


This repository hosts the draft version of the PP-Module for WLAN
Clients based on the
https://commoncriteria.github.io/pp/QQQQ/QQQQ-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
PP-Module is intended for use with the following Base-PPs:

* General Purpose Operating System (GPOS) Protection Profile
* Mobile Device Fundamentals (MDF) Protection Profile

This repository is used to facilitate collaboration and development on
the draft document. See the link:#Release-Version[release] section if
you are looking for the officially released version for evaluations. A
list of products that have passed evaluation against this Protection
Profile can be found
https://www.niap-ccevs.org/Profile/Info.cfm?PPID=386&id=386[here].

=== Draft Version

* https://commoncriteria.github.io/pp/wlanclient/wlanclient-release.html[PP-Module
for WLAN Client v1.0] (html)
* https://commoncriteria.github.io/pp/wlanclient/wlanclient-release.pdf[PP-Module
for WLAN Client v1.0] (pdf)
* https://commoncriteria.github.io/pp/wlanclient/wlanclient-sd.html[Supporting
Document] (html)
* https://commoncriteria.github.io/pp/wlanclient/wlanclient-sd.pdf[Supporting
Document] (pdf)
* https://commoncriteria.github.io/wlanclient[QuickBuild Output
Directory]

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=386&id=386[PP-Module
for WLAN Client]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community.

* https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/wlanclient/issues[repository issue
tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/wlanclient.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
